### ISSUE TITLE
Missing documentation for *_questitem tables

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#105]
The following tables:

- `creature_questitem`
- `gameobject_questitem`

don't have any documentation. Also their pages on the TC wiki are empty.

**Comment by degenesis** [comment]
creature_questitem : Creatures that drop quest items while a certain quest is accepted.
gameobject_questitem: Gameobjects that can be looted for a quest item while a certain quest is accepted.

**Comment by FrancescoBorzi** [comment]
@degenesis thanks, would you like to add it to the wiki page?

**Comment by degenesis** [comment]
wouldnt know how, no good at html

**Comment by FrancescoBorzi** [comment]
@degenesis it's not html, it's just markdown (same as github):

https://github.com/azerothcore/wiki/tree/master/docs
