### ISSUE TITLE
Database documentation

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#11]
It is very important for our users and contributors to have access to a solid, reliable documentation that is updated with latest master version.

We are proceeding with drafting the Database documentation through the following steps:

- [x] Import the documentation from TC
- [x] Create indexes
- [ ] Fix anchors
- [ ] Fix the layout of tables
- [ ] Fix the documentation whenever is different from TC

The last two steps take time and cannot be done all at once, for this reason we need your help. Please help the project by improving the doc: you can edit the files online via github and easily propose your changes. We will appreciate.

- [DB world](http://www.azerothcore.org/wiki/database-world)
- [DB characters](http://www.azerothcore.org/wiki/database-characters)
- [DB auth](http://www.azerothcore.org/wiki/database-auth)

**Comment by Helias** [comment]
I'll fix the layout of tables

**Comment by Yehonal** [comment]
is this still valid? 

Close it for now
