### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#13]
Can we have a wiki placeholder on azerothcore, so that we click wiki and we are redirected to here ? each time i have to ctrl+f the readme :P

**Comment by Pondaveia** [comment]
Isn't this already done at the main page? Or do you want a big CLICK ME kind type of image?

**Comment by FrancescoBorzi** [comment]
http://www.azerothcore.org/ -> info -> wiki

**Comment by BarbzYHOOL** [comment]
No i'm speaking about Devs who mostly spend their time on github, they don't visit the website (I did this a lot of time so I bet real devs do it too)

99% of the repos have a github wiki, so we should have the github wiki with one single page that redirect to our wiki

**Comment by FrancescoBorzi** [comment]
good idea

**Comment by FrancescoBorzi** [comment]
done: https://github.com/azerothcore/azerothcore-wotlk/wiki/

**Comment by BarbzYHOOL** [comment]
lol i was thinking of doing it recently, ty
