### ISSUE TITLE
AreaTrigger documentation missing

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/wiki#136]
The wiki is missing this page:
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129955/AreaTrigger

This is referred to in the description of various "areatrigger_*"-tables, e.g.: http://www.azerothcore.org/wiki/areatrigger_scripts

**Comment by Helias** [comment]
Are you sure? http://www.azerothcore.org/wiki/DBC-AreaTrigger
Are there any tables related to AreaTrigger missing?

**Comment by Stoabrogga** [comment]
I don't know, just saw that the links are not leading anywhere and thought it is missing:
http://www.azerothcore.org/wiki/areatrigger_involvedrelation
http://www.azerothcore.org/wiki/areatrigger_scripts
http://www.azerothcore.org/wiki/areatrigger_tavern
http://www.azerothcore.org/wiki/areatrigger_teleport

So it seems that only the links have to be updated.
