### ISSUE TITLE
Action OVERRIDE_SCRIPT_BASE_OBJECT can crash the core

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#159]
Under the voice `SMART_ACTION_OVERRIDE_SCRIPT_BASE_OBJECT` there is:

> WARNING: CAN CRASH CORE, do not use if you don't know what you are doing

we should understand if this is still true and, if there is a crash, fix it

http://www.azerothcore.org/wiki/smart_scripts#action_type

**Comment by Stoabrogga** [comment]
As far as I understand the implementation you can exchange the base object of the script with the target by using this action. This means that the further script is running on a different object which could result in unpredictable behaviour if you don't know exactly what you're doing. So the warning is correct and should be preserved.

I also checked the DB and this action is not used anywhere.

**Comment by FrancescoBorzi** [comment]
No way to prevent the crash? If not, we can close this

**Comment by Stoabrogga** [comment]
No, because you can do all sorts of strange stuff here. Don't know why this was actually introduced, can't think of a scenario where this could be of any use. But perhaps I'm just not creative enough 😆 .
