### ISSUE TITLE
Change obsolete screenshot

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#172]
Need to change 3 screenshots here http://www.azerothcore.org/wiki/creature_text#type :P

**Comment by Yehonal** [comment]
still valid?

**Comment by BarbzYHOOL** [comment]
yes

**Comment by Yehonal** [comment]
Can you change it?

**Comment by Kitzunu** [comment]
Give me new images and I will PR it x)

**Comment by BarbzYHOOL** [comment]
just need to change "uncle trinity" to smthg else

**Comment by pangolp** [comment]
I would not put images, what I would do, is look for the colors, and through CSS, format it. But without images.
