### ISSUE TITLE
Commands not implemented

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#181]
Commands:
honor add kill
honor update

Do not exist in our core

**Comment by Yehonal** [comment]
Can you link the page with the issue please? anyway, feel free to edit the file by yourself, it's the reason of wiki existance

**Comment by BarbzYHOOL** [comment]
> anyway, feel free to edit the file by yourself

ah ok didn't know (  https://github.com/azerothcore/wiki/commits?author=BarbzYHOOL )

http://www.azerothcore.org/wiki/GM-Commands is the page, i didn't do it cause it was in a hurry and i also thought it might be interesting to port the commands

**Comment by Yehonal** [comment]
For now, since they don't exist, is better to remove them and. Close the issue IMHO
