### ISSUE TITLE
Duskbat and some other npcs are not supposed to be skinnable

### ISSUE THREAD

**Issue by dady172172** [azerothcore/wiki#192]
**Describe the bug**
Duskbat and some other npcs are not supposed to be skinnable.

**To reproduce**
Skin a Duskbat entry 1512 

**Expected behavior**
Duskbat is not supposed to be skinnable

**Screenshots**
none needed

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: Chrome

**Additional context**

Came across this while googling if duskbats are skinnable. I didn't think i could back in the day on retail. I ran the quarry on there and it fixed some npcs that are not supposed to be skinnable.
[https://github.com/TrinityCore/TrinityCore/issues/15917] 
here is the sql:
```sql

-- Remove skinning_loot_template 100008 from non-skinnable beasts:
UPDATE `creature_template` SET `skinloot`= 0 WHERE `skinloot`= 100008 AND `entry` NOT IN (1042,1043,1069);

UPDATE `skinning_loot_template` SET `Comment`='Light Leather' WHERE `Item`= 2318 AND `Entry` IN (3098,3124);
UPDATE `skinning_loot_template` SET `Comment`='Ruined Leather Scraps' WHERE `Item`= 2934 AND `Entry` IN (3098,3124);
```

**Comment by FrancescoBorzi** [comment]
@dady172172 have you tested this SQL code? if yes, can you please [open a PR](http://www.azerothcore.org/wiki/How-to-create-a-PR)

**Comment by dady172172** [comment]
never done a PR before. I'm having issues with git commit. I don't know how to edit this in the gitbash window. [image](https://prnt.sc/r9ovrj)

**Comment by FrancescoBorzi** [comment]
@dady172172 just use: `git commit -m "fix: duskbat and some other npcs"`

**Comment by BarbzYHOOL** [comment]
dady hit me up on discord if you need help with git

**Comment by BarbzYHOOL** [comment]
also this is posted in the WRONG repository, please repost in our core repository so i can put correct labels
