### ISSUE TITLE
Bug in the wiki

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#196]
@Yehonal please, have a look maybe it's a bug in the wiki, and that's why we need a way to preview the changes in the wiki :'(

- When someone makes a page, we check the preview in github markdown https://github.com/Kitzunu/wiki/blob/d06f93231609093c614a3a4000d8da4a61d7238b/docs/MySQLtypesC%2B%2B.md result = fine
- But now look at the page http://www.azerothcore.org/wiki/MySQLtypesC++ fucked up!!!

_Originally posted by @BarbzYHOOL in https://github.com/azerothcore/wiki/pull/191#issuecomment-595432237_

**Comment by Kitzunu** [comment]
You bugged Yehonal enough for it to be fixed :P
