### ISSUE TITLE
[GENERAL] Add ChrRaces file

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#198]
do we have this page or similar, or not yet?

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129966/ChrRaces

**Comment by Helias** [comment]
I don't think so, we have only some data described but probably not in a structured way.

**Comment by BarbzYHOOL** [comment]
there is also chrclasses
and they're referred in playercreateinfo_ tables

however i always found these pages quite horrible to look at, I think we just need to put the info we need from these tables (aka the flags for classes and races) in the same page

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/wiki/pull/85

**Comment by BarbzYHOOL** [comment]
Do we have the pages now @Kitzunu ?

**Comment by Kitzunu** [comment]
Not that I am aware of, I have not created any DBC info

**Comment by pangolp** [comment]
Issue resolved.
