### ISSUE TITLE
Missing columns but they are worthless

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#210]
Pages creature and gameobject are missing columns (2 to 4)
They are also missing on TC wiki

zoneId  (completely useless column)
areaId  (completely useless column)
ScriptName
VerifiedBuild (but do we really need that piece of shit?)

Imo the 3 useless columns should be removed and eventually zoneid/areaid moved to a module that display extra information because I think they are not used in the core at all

Only 13 rows / 146000 are using zoneId and areaId in `creature`

**Comment by Kitzunu** [comment]
They exist in the wiki
