### ISSUE TITLE
Players connections limitations

### ISSUE THREAD

**Issue by Helias** [azerothcore/wiki#212]
We need to add this https://github.com/azerothcore/azerothcore-wotlk/issues/2573 in the wiki somewhere

**Comment by Kitzunu** [comment]
still valid?

**Comment by Helias** [comment]
I don't know, I never overcome 1-2 k players

**Comment by FrancescoBorzi** [comment]
I'd close this unless someone can confirm the problem on latest AC

**Comment by Kitzunu** [comment]
I dont understand it and I havent heard of it anymore since. So I will close this
