### ISSUE TITLE
GM commands randomly ordered

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#213]
Reorganize the commands by LOGIC (or alphabetical order)

example: .cheat commands are randomly inserted, hard to browse

http://www.azerothcore.org/wiki/GM-Commands

**Comment by Kitzunu** [comment]
I think alphabetical order is best, since it would follow the structure of the page

**Comment by BarbzYHOOL** [comment]
depends on the commands though, but alphabetical would solve most of the issues I guess (unless there is a stupid command like the old "morph/demorph")

**Comment by steenburgh** [comment]
Alphabetical order will be by far the easiest to maintain. I think we should put everything in alphabetical order by default and make as few exceptions as possible. I think morph/demorph or similar dox/undox would be useful to group though.

**Comment by steenburgh** [comment]
I'm currently working on alphabetizing commands. In the future, it might be a good idea to group commands by category, but that'd be a lot more work.

**Comment by BarbzYHOOL** [comment]
now they have been alphabetized, but if someone ever wants to work on grouping them by logical order, it's gonna be a not so easy job!
