### ISSUE TITLE
WE NEED YEHONAL TO FIX THIS

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#218]
http://www.azerothcore.org/wiki/smart_scripts there is a huge issue with this page around "target type" 

but we can't fix because it's SHIT

we have no way to preview  so we can't fix it at ALL and so only @Yehonal  can fix it -_- (it's his custom wiki)

it's been like that for months already

**Comment by Yehonal** [comment]
you should be able to fork this repo and edit/test on your gh-pages, then make a PR. It's a normal github page website with some jeckyll code, nothing else.

I've read the code but it's huge, I'm pretty sure it's something related to a missing table-closing but I can't figuring it out.

**Comment by Yehonal** [comment]
Should be fixed:

https://github.com/azerothcore/wiki/commit/c685f900a468b3a2a90e27d9592be1b72855420c

please check other pages too. The parser is different now

**Comment by BarbzYHOOL** [comment]
fixed on that page, thank you!
