### ISSUE TITLE
item_template column unexplained ItemLimitCategory

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#241]
Can anyone find what is this column for in item_template: `ItemLimitCategory` ? then fill the wiki

i quickly checked and can't find

**Comment by Helias** [comment]
It's related to a DBC file if you use Keira3 you can also have the list of the predefined values.
I am not sure but it probably shows the "count" and the "unique/limit-count" property of an item.

Like this one with `ItemLimitCategory 3`:
![image](https://user-images.githubusercontent.com/519778/83980806-e8e74000-a918-11ea-91f1-947e22df7090.png)

or this one with `itemLimitCategory 4`:
![image](https://user-images.githubusercontent.com/519778/83980828-1338fd80-a919-11ea-9416-93ef59aa68e8.png)

A player can have only one healthstone in his bag, similarly, a mage can have only one mana gem.
But there are several item "mana gem" like 10, similarly, there are several kinds of "healthstone", the fact is, they are mutual exclusive, if I make a mana gem lvl 45 I can't make another mana gem lvl 30 or 50, I can't only have one mana gem in my bag and use only one.

But I think, that there is no a "generic explanation" for this field :(

**Comment by BarbzYHOOL** [comment]
ok very interesting, if you didn't explain with that example i wouldn't have understood

Can you write it in the wiki somehow? Basically say that it is based on a DBC value that defines how many iteration of an item belonging to a specific category can the user possess. Example: 1 mana gem (includes lesser mana gem, greater mana gem, major mana gem etc)

**Comment by Helias** [comment]
Agree, this field is not so "easy' to understand, if I didn't develop/use Keira3 I never know.

I made the PR, review it and merge :P
