### ISSUE TITLE
Weird header in home file

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/wiki#267]
![image](https://user-images.githubusercontent.com/24550914/88310503-08db9300-cd10-11ea-8682-db2fa5997bb5.png)
I dont know how this happened since we cant see it in the home.md file but 🤷

**Comment by pangolp** [comment]
I don't know why that part came up. Possibly an error occurred while making the deploy, because in local, that message does not appear. In fact, I thought that it was solved with the pull request code, but apparently, it still appears.

**Comment by Kitzunu** [comment]
Can we revert https://github.com/azerothcore/wiki/pull/379 ? It made it worse

**Comment by Kitzunu** [comment]
Perhaps if we remove the entire line it would fix it lol

**Comment by pangolp** [comment]
If you remove the line, you no longer have the index at the top. But you can do the test if you want. I don't have the feeling that it has gotten worse, it's more, I don't know if there was so much detail in the index, as it is currently shown. It wasn't really the solution I was waiting for.

**Comment by pangolp** [comment]
I get the feeling that it is a mistake in the deploy, because when I pick up the local server with docker, it doesn't show me those lines.

**Comment by Kitzunu** [comment]
yea, but with your PR it got even worse on the wiki

**Comment by pangolp** [comment]
The only thing I see is that now it has more indexes, nothing else. But if you think it looks so bad, as to leave it, revert. In the end, the pull request was for something else, not that.

**Comment by pangolp** [comment]
The problem is not in the wiki, but in the template that the wiki uses, I think. For the moment, I would have removed it, until the problem was fixed, and then I would have added it again.

**Comment by pangolp** [comment]
https://github.com/Drassil/git-wiki-theme/commit/a66783cef7766aea9137c09f753563b7a29cabe9#diff-91e2bafaedfa4f9acb4cdb97667985cedfd6f90f1885edb09d97d5dd835cb076

**Comment by pangolp** [comment]
Apparently, the content, before, was generated in a static way, and then the component was modified. https://github.com/azerothcore/wiki/commit/42556f199d5a8bae4f5ed6616dc0d6563e527647#diff-325758e5b66cac4e518c4c003ae04d0992e762ff9fe610fde3828c3718e6d4b8

**Comment by Yehonal** [comment]
https://github.com/Drassil/git-wiki-theme/blob/master/_includes/git-wiki/components/toc/toc-lib.html#L101 

This is the line that generates that text

I'm investigating on it

**Comment by Yehonal** [comment]
The official wiki site doesn't have that issue: http://www.drassil.org/git-wiki/main_page 

Probably it's something with our theme...let's check

**Comment by pangolp** [comment]
Locally I don't have that problem either.

**Comment by Yehonal** [comment]
It can be related to the GFM markdown, this is the only difference between the local and the remote platform in your case. 

In fact if you check this line: https://github.com/Drassil/git-wiki-theme/blob/master/_includes/git-wiki/components/toc/toc-lib.html#L108

it says: "markdownify", let me see if we can get rid of that part somehow

**Comment by pangolp** [comment]
Excellent news.

**Comment by Yehonal** [comment]
Solved by removing the id xD

https://github.com/azerothcore/wiki/commit/a10ad5804b78a50802d597edcd09df5dc6a3395b

**Comment by pangolp** [comment]
hahaha, the wonders of technology xD.

**Comment by Kitzunu** [comment]
Okay now we need to figure out how to remove it completely because this is not okay
![image](https://user-images.githubusercontent.com/24550914/104964390-9dcbfa00-59dc-11eb-9c31-edc907c1d553.png)
![image](https://user-images.githubusercontent.com/24550914/104964404-a4f30800-59dc-11eb-8842-f3bef533c37b.png)

Why is this not okay? 
2 reasons:
1. looks bad af when it is horizontal
2. it is not needed when this information is specified in the tables below!
![image](https://user-images.githubusercontent.com/24550914/104964466-c2c06d00-59dc-11eb-8289-f9f75349f34e.png)

**Comment by pangolp** [comment]
Yes, but the content, what it takes, is the <h1> so to speak, that has a web, and not all the pages have links. With that, we could have access to the zones inside the page or know what information it has. The horizontal theme, can be by the class `inline`.

**Comment by pangolp** [comment]
I was looking, that puts them horizontal, when you use lists, that is, when you write: `1.`, `2.`, e.t.c

**Comment by Kitzunu** [comment]
Sure a feature like this can be good on some pages.

but having a table of contents on these pages, plus pages that only have one header is just looking bad.

I would also argue that the only real use of this is in the entire installation guide. However when I have time I want to rewrite it all to make more sense and by then it won't be needed.

**Comment by Yehonal** [comment]
the table of content should always be used

But if you want to disable it in certain pages we can use jekyll features to set a variable in page header and selectively disable it

**Comment by pangolp** [comment]
Perhaps if you give it another focus, it will then lose its meaning, but the way it is diagrammed today, it works. The only thing, that would reduce the `h_max` to 2, so that it does not show so many levels. Because that was a modification I made, when I was looking for a solution to the problem. https://github.com/azerothcore/wiki/pull/383

**Comment by pangolp** [comment]
> the table of content should always be used
> 
> But if you want to disable it in certain pages we can use jekyll features to set a variable in page header and selectively disable it

I think that if we reduce the amount, it will not look so ugly haha.

**Comment by Yehonal** [comment]
For example: 

by setting a custom variable in front-matter, like this:
https://jekyllrb.com/docs/front-matter/#custom-variables

then with an ` if page.ourvariable` on this line: https://github.com/azerothcore/wiki/blob/master/_layouts/azerothcore.html#L38

we can disable the TOC

**Comment by Kitzunu** [comment]
Sure, we should really disable them on all database wikis

**Comment by Yehonal** [comment]
If you can create this simple PR would be great, I have very limited time

**Comment by pangolp** [comment]
Yes, in those files that have structure, it would not be necessary, because generally we already put the links in the same table.

**Comment by Kitzunu** [comment]
@pangolp can you create a PR for this?

**Comment by pangolp** [comment]
> @pangolp can you create a PR for this?

Yes, let me read well what Yenohal put, and I will try to put together the PR. But first, please approve this one, so that it does not generate conflicts later, because I am touching the same file. https://github.com/azerothcore/wiki/pull/383
