### ISSUE TITLE
[GENERAL] migrating script from TC to AC and how to fix related incompatibility

### ISSUE THREAD

**Issue by Helias** [azerothcore/wiki#273]
We need to write a page to help the developers to migrate script from TC to AC.
Like...

`ObjectGuid` -> `uint64`

`uint32 action = GetGossipActionFor(player, gossipListId);`
becomes:
`uint32 action = player->PlayerTalkClass->GetGossipOptionAction(gossipListId);`

`spawnDist` -> `wander_distance`

To convert TC.`creature_template` into AC.`creature_template` you have to remove these fields:
`BaseVariance, RangeVariance, ExperienceModifier`

`#include "Random.h"` -> `#include "Util.h"`

etc.

**Comment by FrancescoBorzi** [comment]
..or import the `ObjectGuid` feature? :D

**Comment by Helias** [comment]
I think that if everyone will contribute o this we will have a full list of things to migrate, so a big work, for now, we can use this `workaround` to solve the compatibility and port more scripts from TC

**Comment by Kitzunu** [comment]
Closing

Most things have or are in the making of being ported to AC.

Also doing a list like this would be huge work to maintain for two projects that always evolve...
