### ISSUE TITLE
Missing page "UpdateFields"

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#280]
Port this page:
https://trinitycore.atlassian.net/wiki/display/tc/UpdateFields

the only usage i know of is with `debug setvalue`	and `debug Mod32Value`	but might be useful for other things

**Comment by pangolp** [comment]
File created, waiting to be reviewed.
I uploaded a screenshot, so you can appreciate it.
I hope it will be useful for you.

**Comment by Helias** [comment]
Can we close this? @pangolp @BarbzYHOOL

**Comment by pangolp** [comment]
I think so. Since the file has already been created.
