### ISSUE TITLE
quest_template_locale not update.

### ISSUE THREAD

**Issue by mpfans** [azerothcore/wiki#289]
https://www.azerothcore.org/wiki/quest_template_locale 

The latest table structure is the following image
https://discordapp.com/channels/@me/774206670540374028/774207014318505986

**Comment by mpfans** [comment]
![unknown](https://user-images.githubusercontent.com/18187177/98357265-ed4a8d00-205f-11eb-9129-3a123745b2b8.png)

**Comment by pangolp** [comment]
I have just updated the table documentation.

**Comment by FrancescoBorzi** [comment]
@pangolp can this be closed then?

**Comment by pangolp** [comment]
You could say that. I have just made the last modifications they asked me for, anyway, I would wait maybe for the merger to be done. @FrancescoBorzi

**Comment by pangolp** [comment]
The information is already updated.
Thanks for the report @mpfans
Thank you for the feedback @FrancescoBorzi
