### ISSUE TITLE
Where are the docs imported from TC?

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#32]
I don't find the page I edited myself (account page, imported from TC and modified by me)

I don't know how to access them

Plz tell me the link

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/wiki/issues/11

**Comment by BarbzYHOOL** [comment]
?????????????????? @FrancescoBorzi

**Comment by BarbzYHOOL** [comment]
I found some links on that other issue but many links point to the OLD stuff imo (like the command.md page, it's empty)
