### ISSUE TITLE
[TODO] Create how-to extract spells from DBC and import to the spell_dbc table

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#447]
I've created this placeholder:

https://github.com/azerothcore/wiki/blob/master/docs/importing-spell-dbc.md

so I can already include this link in Keira3:

https://www.azerothcore.org/wiki/importing-spell-dbc

**Comment by pangolp** [comment]
Has this issue been resolved? Because it looks like the page has already been created.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/wiki/commit/7f57c9c3230a6656d8a9985421566b5fe422500e
