### ISSUE TITLE
Improve backend structure

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/wiki#449]
It would be nice if the wiki could be built kind of like https://github.com/github/docs/tree/main/content with subfolders that contain f.ex all "database_world" files and one for "auth_database" etc, this way we kan keep track more of the content we have and make sure we don't have duplicate, or invalid pages more easily

**Comment by Kitzunu** [comment]
Or we could adapt their wiki code as it is released under MIT, because ngl https://docs.github.com/en looks clean compared to our :D

**Comment by FrancescoBorzi** [comment]
cc @Yehonal

**Comment by Kitzunu** [comment]
even better if the urls would be for example /wiki/world_db/creature_template where world_db is a subfolder.
And if a .md file is the same name as a subfolder, the /wiki/world_db/ page would become that

**Comment by Yehonal** [comment]
We can use permalinks for this maybe https://jekyllrb.com/docs/permalinks/

Otherwise, if we want to move them under folder we should remember to use the `redirect_from` to avoid losing SEO on google

**Comment by Kitzunu** [comment]
so if I understand permalinks correctly, if I add 
```
---
permalink: /world/
---
```
It would be wiki/world/page? even if I have a file called "world"?

**Comment by Kitzunu** [comment]
it doesn't, I tried

**Comment by Yehonal** [comment]
with the permalink, you override the entire path, so you should put the full URL: https://jekyllrb.com/docs/permalinks/

However, a subfolder would work too. The Github Doc website uses subfolders.
