### ISSUE TITLE
[GENERAL] Memory Usage Update Needed for Wiki

### ISSUE THREAD

**Issue by Quest79** [azerothcore/wiki#459]
Memory usage need to be updated. 
On windows 10 with a fresh Docker install and a fresh as of this post date install of master with 0 players online I see **4.9** (initial) to - **5.3**GB usage (as of this sentence). No logins, nothing edited or changed, from a pure start.

I have no issues with this usage, but it is helpful for people purchasing ram/instances/remotehardware/whatever to know real ram needs. 

Wiki pages in question:
https://www.azerothcore.org/wiki/Memory-Usage (if this estimate if for a non-docker install, it should be cleared up what the differences are in the supported install types) 
https://www.azerothcore.org/wiki/Install-with-Docker (Scroll down to memory usage, if macOS differs from other install environments this should be cleared up)

**Comment by FrancescoBorzi** [comment]
@Quest79 yes, it should be specified that those values are for the standard setup (no docker). And we should also mention that Docker takes some extra overhead when used on WIndows or macOS.

PRs are welcome ;)

**Comment by Kitzunu** [comment]
there is never a good way to estimate how much memory it will consume
