### ISSUE TITLE
creature_text_locale column name is incorrect

### ISSUE THREAD

**Issue by mpfans** [azerothcore/wiki#467]
**Describe the bug**
https://www.azerothcore.org/wiki/creature_text_locale

Column name is incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/18187177/117319861-48015c00-aebe-11eb-81ca-5d31e5c6dabd.png)

![image](https://user-images.githubusercontent.com/18187177/117319891-4fc10080-aebe-11eb-9378-58a0937ce1d4.png)

**Comment by pangolp** [comment]
Confirmed, now I will try to update the page, thanks for the report.

**Comment by mpfans** [comment]
The new core should not use this table, now it is broadcast_ text_ locale

**Comment by pangolp** [comment]
Right, it doesn't use it, but for the moment it exists, so we have to update it anyway. Finally, when it is removed from the emulator, the file can be deleted.
