### ISSUE TITLE
Suggestion: Dark Theme

### ISSUE THREAD

**Issue by Branel** [azerothcore/wiki#480]
I think the wiki would be even better if it had a possibility to have dark theme, for instance it can detect what your current theme in Windows 10 and then change the theme to dark mode if that's what you have, the implementation itself is very easy and I am happy to open up a PR and work on it for a while and get it to a stage where everybody agrees on it, it's quite a lot of busy work but with enough time anything is possible. There would of course also be a button or something similar to disable the dark mode incase any user has a dark mode theme but doesn't want it on the wiki or if CSS cannot detect your current theme.

Want to see a good example of what my suggestion is? https://docs.discord4j.com/ Here is one of the websites I think personally implemented dark theme in the best way possible, except github of course :D

Happy to hear your thoughts and some feedback on the idea.

**Comment by Helias** [comment]
I really like the dark themes, for the AC wiki I applied this https://github.com/StylishThemes/GitHub-Dark using the Stylus plugin.
But yes, we need to integrate an official dark theme for the wiki.

**Comment by Kitzunu** [comment]
Should maybe be on Drassil repo? cc @Yehonal

**Comment by Yehonal** [comment]
Yes please, open an issue here: https://github.com/Drassil/git-wiki-theme

We can start to investigate it. I close this issue here

**Comment by Eldarix** [comment]
Dark mode rules, always :)
