### ISSUE TITLE
CSS - Big empty space on the left

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#5]
Big empty space on the left like 33% of the page is just blank

This is the responsible:

```
.git-wiki-page {
    padding-left: 320px;
```

**Comment by Yehonal** [comment]
this is a suggestion by @FrancescoBorzi, we're using the github css to keep the same page dimension of original document

**Comment by BarbzYHOOL** [comment]
put a naked girl on the left then...

**Comment by Yehonal** [comment]
Done

![image](https://user-images.githubusercontent.com/147092/53119852-b2818800-3550-11e9-9661-afee9fd990fa.png)
