### ISSUE TITLE
usable sitemap

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/wiki#518]
100 times better with https://github.com/azerothcore/wiki/issues/449 too

first of all it would be nice with a sitemap, second of all it would be nice if the CI could update the sitemap if a file was added, deleted =)

**Comment by Yehonal** [comment]
We already have a generated site map for the wiki

https://www.azerothcore.org/wiki/sitemap.xml

It's part of the git wiki system

**Comment by Kitzunu** [comment]
cool, part of the idea done then.

Would also be nice to have it as a "readable" file with subgroups for example world_db contents etc. (Kinda where a directory structure could come in play I guess)

**Comment by Kitzunu** [comment]
a workable backend and interface

**Comment by Yehonal** [comment]
Could you make an example of how it should be? 

The generation of the sitemap is done here and it uses a Jekyll script that should be enough, I do not see the need for a BE here.
