### ISSUE TITLE
Clarify Docker production services usage

### ISSUE THREAD

**Issue by mserajnik** [azerothcore/wiki#520]
**Is your feature request related to a problem? Please describe.**

The [_Install with Docker_](https://www.azerothcore.org/wiki/Install-with-Docker) article does a good job of getting a basic setup running with Docker.

However, I've noticed that there are [_production_ services configured in the `docker-compose.yml`](https://github.com/azerothcore/azerothcore-wotlk/blob/62ae4b53e61bbe9c7e6e3a2a210954cfe9f3df26/docker-compose.yml#L196-L292). These aren't used when starting the containers using `./acore.sh docker start:app` (or `./acore.sh docker start:app:d`) and instead have separate commands (`./acore.sh docker prod:build`, `./acore.sh docker prod:up` etc.). They also aren't mentioned in the article.

I assume these _production_ services are better/optimized for running in an actual production environment (i.e., a server that runs 24/7 with multiple people regularly connecting to it)?

If so, it would be great to have another section/article about how to use those services and what the benefits of running them instead of the _app_ services that are run when following the _Install with Docker_ article are.

**Describe the solution you'd like**

Extend the [_Install with Docker_](https://www.azerothcore.org/wiki/Install-with-Docker) article with information about the _production_ services (how to use them, what the benefits of using them are, when it might _not_ be a good idea to use them etc.).

**Describe alternatives you've considered**

Instead of extending the existing article, the information could also go in a separate one (in case there are enough differences from the "regular" _app_ services Docker setup that it warrants having a second article).

**Comment by FrancescoBorzi** [comment]
@Yehonal

**Comment by Kitzunu** [comment]
Going to close as it has been revamped
