### ISSUE TITLE
Add (Translation\ES): Documents in Spanish

### ISSUE THREAD

**Issue by pangolp** [azerothcore/wiki#539]
**Is your feature request related to a problem? Please describe.**
No, it is not necessarily a problem, it is simply to be able to offer more information in other languages, not only in English.

**Describe the solution you'd like**
Currently, the wiki is displayed in English, which is good, but it would be interesting to incorporate other languages. Mainly for those people who are not fluent in the language, but still want to collaborate or learn.

**Describe alternatives you've considered**
Create a folder with the Spanish language (/docs/es) and make inside it, the translations of the original files.

**Additional context**
This is the list of files to be translated.

- [ ] account_data.md
- [ ] account_instance_times.md
- [ ] account_tutorial.md
- [ ] ac-dashboard-core-installation.md
- [ ] achievement.md
- [ ] achievement_criteria.md
- [ ] achievement_criteria_data.md
- [ ] achievement_dbc.md
- [ ] achievement_reward.md
- [ ] achievement_reward_locale.md
- [ ] acore_string.md
- [ ] add-a-module.md
- [ ] addons.md
- [x] [arch-linux.md](https://www.azerothcore.org/wiki/es/arch-linux)
- [ ] areatable.md
- [ ] areatrigger.md
- [ ] areatrigger_involvedrelation.md
- [ ] areatrigger_scripts.md
- [ ] areatrigger_tavern.md
- [ ] areatrigger_teleport.md
- [ ] arena_team.md
- [ ] arena_team_member.md
- [ ] auctionhouse.md
- [x] [aws-tutorial.md](https://www.azerothcore.org/wiki/es/aws-tutorial)
- [ ] banned_addons.md
- [ ] bash_system.md
- [ ] battleground_deserters.md
- [ ] battleground_template.md
- [ ] battlemaster_entry.md
- [ ] bit-and-bytes-tutorial.md
- [ ] bountysource.md
- [ ] broadcast_text.md
- [ ] broadcast_text_locale.md
- [ ] bugreport.md
- [ ] calendar_events.md
- [ ] calendar_invites.md
- [ ] channels.md
- [ ] channels_bans.md
- [ ] channels_rights.md
- [ ] character_account_data.md
- [ ] character_achievement.md
- [ ] character_achievement_progress.md
- [ ] character_action.md
- [ ] character_arena_stats.md
- [ ] character_aura.md
- [ ] character_banned.md
- [ ] character_battleground_data.md
- [ ] character_battleground_random.md
- [ ] character_brew_of_the_month.md
- [ ] character_declinedname.md
- [ ] character_entry_point.md
- [ ] character_equipmentsets.md
- [ ] character_gifts.md
- [ ] character_glyphs.md
- [ ] character_homebind.md
- [ ] character_instance.md
- [ ] character_inventory.md
- [ ] character_pet.md
- [ ] character_pet_declinedname.md
- [ ] character_queststatus.md
- [ ] character_queststatus_daily.md
- [ ] character_queststatus_monthly.md
- [ ] character_queststatus_rewarded.md
- [ ] character_queststatus_seasonal.md
- [ ] character_queststatus_weekly.md
- [ ] character_reputation.md
- [ ] character_skills.md
- [ ] character_social.md
- [ ] character_spell.md
- [ ] character_spell_cooldown.md
- [ ] character_stats.md
- [ ] character_talent.md
- [ ] characters.md
- [ ] chrclasses.md
- [ ] chrraces.md
- [ ] cmake-options.md
- [ ] command.md
- [x] [common-errors.md](https://www.azerothcore.org/wiki/es/common-errors)
- [ ] conditions.md
- [ ] corpse.md
- [ ] cpp-code-standards.md
- [ ] creature.md
- [ ] creature_addon.md
- [ ] creature_classlevelstats.md
- [ ] creature_equip_template.md
- [ ] creature_formations.md
- [ ] creature_model_info.md
- [ ] creature_onkill_reputation.md
- [ ] creature_questender.md
- [ ] creature_questitem.md
- [ ] creature_queststarter.md
- [ ] creature_respawn.md
- [ ] creature_summon_groups.md
- [ ] creature_template.md
- [ ] creature_template_locale.md
- [ ] creature_template_movement.md
- [ ] creature_template_resistance.md
- [ ] creature_template_spell.md
- [ ] creature_text.md
- [ ] creature_text_locale.md
- [ ] database-keeping-the-server-up-to-date.md
- [ ] database-manual-setup.md
- [ ] database-only-quick-setup.md
- [ ] database-squash.md
- [ ] dbc-areatrigger.md
- [ ] digital-ocean-video-tutorial.md
- [ ] directory-structure.md
- [ ] disables.md
- [ ] dungeon_access_requirements.md
- [ ] dungeon_access_template.md
- [ ] emotes.md
- [ ] environment-variable.md
- [ ] event_scripts.md
- [ ] exploration_basexp.md
- [ ] faction.md
- [ ] factiontemplate.md
- [ ] file-headers.md
- [ ] game_event.md
- [ ] game_event_arena_seasons.md
- [ ] game_event_battleground_holiday.md
- [ ] game_event_condition.md
- [ ] game_event_condition_save.md
- [ ] game_event_creature.md
- [ ] game_event_creature_quest.md
- [ ] game_event_gameobject.md
- [ ] game_event_gameobject_quest.md
- [ ] game_event_model_equip.md
- [ ] game_event_npc_vendor.md
- [ ] game_event_npcflag.md
- [ ] game_event_pool.md
- [ ] game_event_prerequisite.md
- [ ] game_event_quest_condition.md
- [ ] game_event_save.md
- [ ] game_event_seasonal_questrelation.md
- [ ] game_graveyard.md
- [ ] game_graveyard_zone.md
- [ ] game_tele.md
- [ ] game_weather.md
- [ ] gameobject.md
- [ ] gameobject_addon.md
- [ ] gameobject_questender.md
- [ ] gameobject_questitem.md
- [ ] gameobject_queststarter.md
- [ ] gameobject_respawn.md
- [ ] gameobject_template.md
- [ ] gameobject_template_addon.md
- [ ] gameobject_template_locale.md
- [ ] getting-started.md
- [ ] gm_subsurvey.md
- [ ] gm_subsurveys.md
- [ ] gm_survey.md
- [ ] gm_ticket.md
- [ ] gossip_menu.md
- [ ] gossip_menu_option.md
- [ ] gossip_menu_option_action.md
- [ ] gossip_menu_option_locale.md
- [ ] graveyard_zone.md
- [ ] group_instance.md
- [ ] group_member.md
- [ ] groups.md
- [ ] guild.md
- [ ] guild_bank_eventlog.md
- [ ] guild_bank_item.md
- [ ] guild_bank_right.md
- [ ] guild_bank_tab.md
- [ ] guild_eventlog.md
- [ ] guild_member.md
- [ ] guild_member_withdraw.md
- [ ] guild_rank.md
- [ ] holiday_dates.md
- [ ] holidays.md
- [ ] home.md
- [ ] hooks-bash.md
- [ ] hooks-cmake.md
- [ ] hooks-script.md
- [ ] how-to-debug.md
- [ ] how-to-find-trinitycore-commits-of-specific-code-addition.md
- [ ] how-to-import-dbc-data-in-db.md
- [ ] how-to-restart-and-debug.md
- [ ] how-to-spot-db-struct-diff-commits.md
- [ ] importing-spell-dbc.md
- [ ] install-with-docker.md
- [ ] instance.md
- [ ] instance_encounters.md
- [ ] instance_reset.md
- [ ] instance_template.md
- [ ] ip2nation.md
- [ ] ip2nationCountries.md
- [ ] issue-tracker-standards.md
- [ ] item_appearance.md
- [ ] item_effect.md
- [ ] item_enchantment_template.md
- [ ] item_instance.md
- [ ] item_loot_items.md
- [ ] item_loot_money.md
- [ ] item_loot_storage.md
- [ ] item_modified_appearance.md
- [ ] item_refund_instance.md
- [ ] item_set_names.md
- [ ] item_set_names_locale.md
- [ ] item_soulbound_trade_data.md
- [ ] item_template.md
- [ ] item_template_locale.md
- [x] [keira3-internals.md](https://www.azerothcore.org/wiki/es/keira3-internals)
- [ ] lag_reports.md
- [ ] languages.md
- [ ] lfg_data.md
- [ ] lfg_dungeon_encounters.md
- [ ] lfg_dungeon_rewards.md
- [ ] lfg_dungeon_template.md
- [ ] lfg_entrances.md
- [ ] linked_respawn.md
- [ ] linux-core-installation.md
- [ ] linux-keeping-the-server-up-to-date.md
- [ ] linux-requirements.md
- [ ] linux-server-setup.md
- [ ] locales_achievement_reward.md
- [ ] locales_broadcast_text.md
- [ ] locales_creature_text.md
- [ ] locales_gossip_menu_option.md
- [ ] locales_item.md
- [ ] locales_item_set_names.md
- [ ] locales_npc_text.md
- [ ] locales_page_text.md
- [ ] locales_points_of_interest.md
- [ ] locales_quest.md
- [ ] log_arena_fights.md
- [ ] log_arena_memberstats.md
- [ ] log_encounter.md
- [ ] log_money.md
- [ ] logging-configuration.md
- [ ] loot_template.md
- [ ] macos-core-installation.md
- [ ] macos-keeping-the-server-up-to-date.md
- [ ] macos-requirements.md
- [ ] macos-server-setup.md
- [ ] mail.md
- [ ] mail_items.md
- [ ] mail_level_reward.md
- [ ] map.md
- [ ] merge-process.md
- [ ] mysqltypescpp.md
- [ ] npc_spellclick_spells.md
- [ ] npc_text.md
- [ ] npc_text_locale.md
- [ ] npc_trainer.md
- [ ] npc_vendor.md
- [ ] outdoorpvp_template.md
- [ ] page_text.md
- [ ] page_text_locale.md
- [ ] pagetextmaterial.md
- [ ] pet_aura.md
- [ ] pet_levelstats.md
- [ ] pet_name_generation.md
- [ ] pet_spell.md
- [ ] pet_spell_cooldown.md
- [ ] petition.md
- [ ] petition_sign.md
- [ ] phase_area.md
- [ ] player_classlevelstats.md
- [ ] player_factionchange_achievement.md
- [ ] player_factionchange_items.md
- [ ] player_factionchange_quests.md
- [ ] player_factionchange_reputations.md
- [ ] player_factionchange_spells.md
- [ ] player_factionchange_titles.md
- [ ] player_levelstats.md
- [ ] player_xp_for_level.md
- [ ] playercreateinfo.md
- [ ] playercreateinfo_action.md
- [ ] playercreateinfo_item.md
- [ ] playercreateinfo_skills.md
- [ ] playercreateinfo_spell.md
- [ ] playercreateinfo_spell_custom.md
- [ ] points_of_interest.md
- [ ] points_of_interest_locale.md
- [ ] pool_creature.md
- [ ] pool_gameobject.md
- [ ] pool_pool.md
- [ ] pool_quest.md
- [ ] pool_quest_save.md
- [ ] pool_template.md
- [ ] project-versioning.md
- [ ] pvpstats_battlegrounds.md
- [ ] pvpstats_players.md
- [ ] quest_details.md
- [ ] quest_greeting.md
- [ ] quest_mail_sender.md
- [ ] quest_objectives.md
- [ ] quest_offer_reward.md
- [ ] quest_offer_reward_locale.md
- [ ] quest_poi.md
- [ ] quest_poi_points.md
- [ ] quest_request_items.md
- [ ] quest_request_items_locale.md
- [ ] quest_template.md
- [ ] quest_template_addon.md
- [ ] quest_template_locale.md
- [ ] quest_tracker.md
- [ ] recovery_item.md
- [ ] reputation_reward_rate.md
- [ ] reputation_spillover_template.md
- [ ] reserved_name.md
- [ ] run-worldserver-and-authserver-in-visual-studio.md
- [ ] scene_template.md
- [ ] script_waypoint.md
- [ ] scripts.md
- [ ] skill_discovery_template.md
- [ ] skill_extra_item_template.md
- [ ] skill_fishing_base_level.md
- [ ] skillline.md
- [ ] smart_scripts.md
- [ ] spawn_group.md
- [ ] spawn_group_template.md
- [ ] spell.md
- [ ] spell_area.md
- [ ] spell_bonus_data.md
- [ ] spell_custom_attr.md
- [ ] spell_dbc.md
- [ ] spell_enchant_proc_data.md
- [ ] spell_group.md
- [ ] spell_group_stack_rules.md
- [ ] spell_learn_spell.md
- [ ] spell_linked_spell.md
- [ ] spell_mixology.md
- [ ] spell_pet_auras.md
- [ ] spell_proc.md
- [ ] spell_proc_event.md
- [ ] spell_ranks.md
- [ ] spell_required.md
- [ ] spell_script_names.md
- [ ] spell_scripts.md
- [ ] spell_system.md
- [ ] spell_target_position.md
- [ ] spell_threat.md
- [ ] spelldifficulty_dbc.md
- [ ] sql-standards.md
- [ ] sql-versioning.md
- [ ] the-modular-structure.md
- [ ] the-staging-branch.md
- [ ] totemcategory.md
- [ ] transports.md
- [ ] trinitycore-to-azerothcore-characters-migration.md
- [ ] unit-testing.md
- [ ] update.md
- [ ] updatefields.md
- [ ] upgrade-from-pre-2.0.0-to-latest-master.md
- [ ] upgrade-from-pre-3.0.0-to-latest-master.md
- [ ] vehicle_accessory.md
- [ ] vehicle_template_accessory.md
- [ ] version.md
- [ ] version_db_characters.md
- [ ] version_db_world.md
- [ ] warden_action.md
- [ ] warden_checks.md
- [ ] waypoint_data.md
- [ ] waypoint_scripts.md
- [ ] waypoints.md
- [ ] wiki-standards.md
- [ ] windows-core-installation.md
- [ ] windows-keeping-the-server-up-to-date.md
- [ ] windows-requirements.md
- [ ] windows-server-setup.md
- [ ] worldstates.md

**Comment by Tony931023** [comment]
Spanish translations for home.md https://github.com/azerothcore/wiki/pull/570/commits/8b9f9ffda8493a117671c8f5d85011a154a0e02c

**Comment by Tony931023** [comment]
@pangolp después cuando tengas un tiempo actualiza la lista de las traducciónes que se han hecho y agrega a la lista secret_digest.md

**Comment by pangolp** [comment]
Les estoy añadiendo enlaces, a las paginas que están traducidas, aunque por desgracia, no puedo hacer que se abran en una pestaña diferente, probé de varias formas, pero hay algo dentro de la wiki, que lo impide, luego veré si puedo encontrar eso, para que se puedan abrir en una pestaña y que sea mejor.

**Comment by pangolp** [comment]
Moví todas las tablas de auth, a este otro issue, y ya lo cerré, porque al parecer, esta completo. https://github.com/azerothcore/wiki/issues/742. Lo que tendríamos que ir viendo, o en base a algún issue que se cree, la posibilidad también de ir actualizando la información.

**Comment by pangolp** [comment]
El menú lateral, lo metí en este otro issue, a modo de ordenar mejor y organizar lo que esta faltando. https://github.com/azerothcore/wiki/issues/746

> The side menu, I put it in this other issue, in order to better order and organize what is missing. https://github.com/azerothcore/wiki/issues/746

**Comment by pangolp** [comment]
It is better to close this topic, because although many translations have been made, later on, a more updated list can be put together.
