### ISSUE TITLE
Use HTTPS on external websites by default, Docker Compose only open TCP ports

### ISSUE THREAD

**Issue by ghost** [azerothcore/wiki#563]
Some websites still don't do HSTS Preloading and clients can still be put at risk from downgrade attacks and MITMs. Instead of relying on the TLS client/browser to upgrade to HTTPS, define its usage already.
Besides, every website just about now includes HTTPS on every link they put. (Browsers will usually warn on HTTP links anyways so should always just add the HTTPS link)

Areas on the wiki that only use HTTP are on the Windows Requirements page, and the Gemfiles downloading gems. However, I have not thoroughly looked for any more.

Docker Compose, without specifying a protocol, will try to open UDP and TCP. For sake of security and less need to open ports that have the potential to be already in use and error out Docker, define both the live reload and the wiki ports as TCP.

**Comment by pangolp** [comment]
@Zanthed Any ideas on how to solve this?

**Comment by Kitzunu** [comment]
Outdated
