### ISSUE TITLE
Improve consistency of server install instructions for each OS, more universal scripting

### ISSUE THREAD

**Issue by ghost** [azerothcore/wiki#564]
For example, the macOS guide builds with `-DTOOLS=1`, however on Linux that option is set to `0`. The same applies with `-DWITH_WARNINGS`.

Also, when cloning the main repo, the repo isn't cloned as `azeroth-server`. Let's find what directory we're in to avoid issues when copy-pasting the command which is a common occurrence for `-DCMAKE_INSTALL_PREFIX`.
We can also simply find where our clang and clang++ binaries are using `which`. Almost always, even when installing directly from source, the install script will symlink the binaries with the common locations and names such as `/usr/bin`.

The sync-wiki script doesn't have any basic error handling. In a rare scenario you can destroy your local repo if one of the commands fail.

**Comment by pangolp** [comment]
@Zanthed Is this issue resolved or is it necessary to apply the changes you mentioned?

**Comment by Kitzunu** [comment]
No longer an issue
