### ISSUE TITLE
Improve formatting on areas of the wiki for readability, spelling fixes, small elaboration on CMake options

### ISSUE THREAD

**Issue by Zanthed** [azerothcore/wiki#565]
The Linux CMake command is not easily readable compared to the macOS one.
Lots and lots of spelling fixes on many pages.

Also elaborate slightly what the CMake options mean. 
e.g. 
PCH = Precompiled Headers, what purpose does disabing EXTRAS do? (usually for debugging), etc.

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/wiki/commit/dc17689bcef62e18dd1ce9dd64d316d604cf8ac6
