### ISSUE TITLE
Page build fails

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/wiki#577]
Currently the page build fails after this commit https://github.com/azerothcore/wiki/commit/e996716ad4b66b4d40e44123711a738789b9a2b8

I initially thought it was due to duplicate redirects but after https://github.com/azerothcore/wiki/commit/01982c495599a03302eba041fcc6089b151b0a6c it is still failing.

At this point I'm unsure to why as the commit only adds .md files and modifies no .yml files.

**Comment by Kitzunu** [comment]
@Yehonal Do you have a clue?

Is there a way to add error logs to page builds to get more info from them?

**Comment by Kitzunu** [comment]
Even tested if it was due to encoding https://github.com/azerothcore/wiki/commit/693b6336955ac7ab0ba8f5aa86071a5f423d5fd5 but didn't help either...

**Comment by Tony931023** [comment]
will this be the error that is giving you @Kitzunu 

Error reading file /srv/jekyll/docs/es/wiki-standards.md: invalid byte sequence in UTF-8

**Comment by Kitzunu** [comment]
How did you get that error message?
Anyhow, yes!

Look here https://raw.githubusercontent.com/azerothcore/wiki/master/docs/es/wiki-standards.md compared to https://github.com/azerothcore/wiki/blob/master/docs/es/wiki-standards.md All � are not UTF-8 characters. Could you change them?

**Comment by Kitzunu** [comment]
@Tony931023

**Comment by Tony931023** [comment]
Trying locally, I no longer got the error converting the files to UTF-8 with the notepad ++, it seems that it gave a problem with the special characters

**Comment by Kitzunu** [comment]
Yes.

Could you make a PR to fix this?

**Comment by Tony931023** [comment]
if in a few minutes I will find them, I think it would be necessary to add in the wiki standards that the documents are UTF-8

**Comment by Kitzunu** [comment]
Yes, I will update the wiki standard to show utf-8

Thank you
