### ISSUE TITLE
help on language management on the wiki

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/wiki#578]
Hello a question, how would it be the language management in the wiki, allow the user to read it in their preferred language

@Yehonal @pangolp @Helias @MathematicalWTF @Kitzunu @FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
I don't know if the user can set a "default language" but we can surely add a link to check the Spanish pages ;)

keep up the good work @Tony931023 !

**Comment by Helias** [comment]
Me too, I am not sure how to set the default language, this is the first case of having a multi-lang version of this wiki, we could find a solution for this.

**Comment by pangolp** [comment]
Once you enter /es/, all the pages appear in Spanish, and if any of them do not exist, the link appears in red. And it even suggests you to create the same one in the repository I think. I think that if you advance a little more in the translations, you can add a select somewhere on the web, possibly in the sidebar with the available languages. But for that, I think it would be important to continue advancing more in the amount of translated documentaries.

**Comment by Kitzunu** [comment]
There is no way for default. I have added links to English/Spanish on the Home page.

https://github.com/Drassil/git-wiki-theme/issues/88
