### ISSUE TITLE
Windows server compilation - CMakeList alteration in order to debug code you write

### ISSUE THREAD

**Issue by jestermaniac** [azerothcore/wiki#621]
In this page https://www.azerothcore.org/wiki/run-worldserver-and-authserver-in-visual-studio where y'all be describing how to debug on windows the server, before doing that, you gotta modify the CMakeLists.txt file in the C:\Azerothcore folder before generating the build directory otherwise the code you finna add and wanna debug won't be make it to the pdb. This means you can't set breakpoints or step over the code etc..

Idk if this shit has to be on the wiki or directly on the repository but I think at least a note on the wiki would be gucci.

![Capture](https://user-images.githubusercontent.com/88903576/129620176-01c459e3-a114-4c2a-ae8e-93b6881574e0.PNG)

**Comment by Kitzunu** [comment]
Well no. As shown in the guide it's using "Debug" and you can also use "RelWithDebInfo" to compile in VisualStudio which  will allow to generate the pdb files.

If this is unclear I can make it clearar.

**Comment by jestermaniac** [comment]
in the guide u be sayin u gotta change to "Debug" or "RelwithDebInfo" in vs but that wont' work to debug code u add to the solution AFTER the cmake part. it won't make it into pdb and u can't set breakpoint over em, u can try if u aint believin me. i had to add that shit into the cmakelist file and redo the build creation for it to work and set bp and to step into/over those lines

**Comment by Kitzunu** [comment]
Yea my bad. We should change it to RelWithDebInfo by default and not release... Will make a PR on the main repo instead

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/7445

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/afb5db6535de95151ac73401c0497bd4eb1d346a
