### ISSUE TITLE
Bug CorpoReality boss Healion raid wip, not  removed in restart 

### ISSUE THREAD

**Issue by NordiKi** [azerothcore/wiki#622]
Testing the Boss Halion, the Twilight Destroyer in Ruby Sanctum

We came across a bug,
When Wiping the raid in Phase 3... when Buff Corporeality starts,
As soon as the Wipa raid, and everyone returning to the boss, it was transparent and with the Corporeality Buff activated... even so we started the boss again... and so repeatedly in the 3rd phase it duplicates the Corporeality buff

The correct thing would be for the boss to restart without the buff and it is not happening

Spell buff: https://www.wowhead.com/spell=74826/corporeality#comments

Npc boss: https://www.wowhead.com/npc=39863/halion

**Additional context**
![WoWScrnShot_081721_232132](https://user-images.githubusercontent.com/89305735/130327366-fc485ed4-66f0-4289-a5c7-e73e72d33229.jpg)
![WoWScrnShot_081721_232132](https://user-images.githubusercontent.com/89305735/130327499-06b8f37e-9fa9-4a40-8e22-563f42e445ee.jpg)

**Comment by Kitzunu** [comment]
Open a bug report here https://github.com/azerothcore/azerothcore-wotlk/issues/new?assignees=&labels=&template=bug_report.yml
