### ISSUE TITLE
creature_template, extra_flags seem incorrect.

### ISSUE THREAD

**Issue by patou01** [azerothcore/wiki#637]
https://github.com/azerothcore/Keira3/issues/1493 See here, it's the same issue basically, but at a different place.

**Describe the bug**

**To reproduce**
1. creature template, flags_extra don't match between code, wiki and keira3

**Expected behavior**
They should match one way or the other.

**Screenshots**
![image](https://user-images.githubusercontent.com/2592673/137598053-3a4d6dcb-2a45-412b-acb8-02ae89b20bc9.png)
![image](https://user-images.githubusercontent.com/2592673/137598054-911e523e-3aa2-413a-a052-871a859b5a9c.png)

![image](https://user-images.githubusercontent.com/2592673/137598059-e53d4e1f-906f-4ccf-9b0f-f8609bfc1d2c.png)

![image](https://user-images.githubusercontent.com/2592673/137598066-a6f5434a-a56d-482f-b367-975f06aa6711.png)
![image](https://user-images.githubusercontent.com/2592673/137598077-9f979500-ab52-42cb-80ae-c37f723ef8b7.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by Helias** [comment]
Thanks for the report, it's a new flag, few seconds ago I also updated the wiki about this ( https://github.com/azerothcore/wiki/pull/636 )

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/wiki/pull/636
