### ISSUE TITLE
holiday_dates not description

### ISSUE THREAD

**Issue by mpfans** [azerothcore/wiki#639]
**Describe the bug**
holiday_dates not description

**Screenshots**
![image](https://user-images.githubusercontent.com/18187177/137651071-7baef355-14a2-4fd9-9ac8-c8e4acd6efa1.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser: [chrome]
 - Version: [22]

**Additional context**
https://www.azerothcore.org/wiki/holiday_dates

**Comment by pangolp** [comment]
I do not really know what this speech is used for. Many of them are missing the description sometimes.
