### ISSUE TITLE
Invalid links on unit testing page

### ISSUE THREAD

**Issue by TellyO3** [azerothcore/wiki#696]
**Describe the bug**
The following links on the [unit testing](https://www.azerothcore.org/wiki/unit-testing) page are invalid:
https://github.com/google/googletest/blob/master/googletest/docs/primer.md
https://github.com/google/googletest/blob/master/googlemock/docs/for_dummies.md
https://github.com/google/googletest/blob/main/googlemock/docs/for_dummies.md

**To reproduce**
1. Go to  [unit testing](https://www.azerothcore.org/wiki/unit-testing) 
2. Click on the specified links
3. See 404 screen

**Expected behavior**
All links on the page should be valid.

**Issue is independent on device**

**Comment by Helias** [comment]
links fixed, thanks for reporting it
