### ISSUE TITLE
Code highlights only work when the specified language is lowercase

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#7]
**Describe the bug**

Writing '''SQL or '''sql (using `) should both work, as it's currently on github:

```SQL
UPDATE `table` SET `field` = 'string value' WHERE `entry` = 10 ;
```

```sql
UPDATE `table` SET `field` = 'string value' WHERE `entry` = 10 ;
```

**Expected behavior**

Both should work, reflecting github behaviour

**Comment by Yehonal** [comment]
Github has a customize kramdown parser i guess. The official documentation of kramdown with rogue highlighter doesn't support uppercase

**Comment by BarbzYHOOL** [comment]
both works in that example xD
