### ISSUE TITLE
Support required

### ISSUE THREAD

**Issue by mpfans** [azerothcore/wiki#704]
The two newly added data tables are not in the wiki. Please provide support

https://github.com/azerothcore/azerothcore-wotlk/commit/7ecd73867419c807c9869ebeb73c7ca4e39cd1c8

**Comment by Helias** [comment]
They already have been added  already, I recently added them in the character list

https://www.azerothcore.org/wiki/mail_server_character
https://www.azerothcore.org/wiki/mail_server_template
