### ISSUE TITLE
[Feature Request]: Add a function on translations.

### ISSUE THREAD

**Issue by pangolp** [azerothcore/wiki#786]
### Is your feature request related to a problem? Please describe.

The translations system, the truth is that it works quite well, maybe later on, another way of doing it will be found, and it will be adapted, but for the moment, it fulfills perfectly the role for which it is being used. However, it would be interesting to know, if it is possible to create some function, inside ruby, to detect if a file, is translated, and to show a message that the same one is also in Spanish for its reading.

### Describe the solution you'd like

Currently, the side menu is updated through a link, to change that part, so that it detects directly a string in the URL, which is /es/ and in that case, it always shows the web in Spanish. Because previously, the menu, when accessing another page, normally returned to English, but now, it always belongs in Spanish. However, we have to enter through the home, to the wiki in Spanish, and I would like to know, if it is possible to make some function, so that if the file is in Spanish, that is to say, inside the directory `es`, it automatically shows a message to him, that the same one also is in Spanish.

### Describe alternatives you've considered

Another option, would be to add back in the sidebar, so that it can be changed by the link, but it really seems to me that at present, it looks and navigates much better than before. Since the URL and translations remain static now.

### Additional context

None

**Comment by pangolp** [comment]
CC @Yehonal

**Comment by pangolp** [comment]
I would like more than anything, to see if you have an option or if you think it could be something interesting. I don't know how hard it will be to do, but if it's something good, I'll look into it. At least now, we have always supported translations, because the menu is no longer changed and is in English by default.

**Comment by Yehonal** [comment]
I'm not sure what kind of mechanism we can use to link different markdown files together. We can script something with Lucid (Jekyll scripting) during the static generation, or dynamically with javascript, maybe using a json. But I do not have an elegant/clear solution for it

**Comment by pangolp** [comment]
> I'm not sure what kind of mechanism we can use to link different markdown files together. We can script something with Lucid (Jekyll scripting) during the static generation, or dynamically with javascript, maybe using a json. But I do not have an elegant/clear solution for it

Don't worry, we'll find a way around it. For the moment, I modified the sidebar, using the URL a few weeks ago. And it looks better. Because before the sidebar was changed automatically, now it is fixed.

**Comment by pangolp** [comment]
This issue has been resolved, I believe. In fact, we have been able to add many translations. I will close it.
