### ISSUE TITLE
[Feature Request]: C++ Code Standards for `switch`

### ISSUE THREAD

**Issue by Synful-Syn** [azerothcore/wiki#790]
### Is your feature request related to a problem? Please describe.

I have read on the wiki about the [C++ Code Standards](https://www.azerothcore.org/wiki/cpp-code-standards) but it does not have any section that describes the preferences about the `switch` statements such as the following.

1) If there is no content needed in the `default` part of the `switch`, should the `default: break;` simply be absent in this case? We currently have an inconsistence between a [`switch` with an empty `default`](https://github.com/azerothcore/azerothcore-wotlk/blob/d0561c56df194aa9eff0f18b237664659153c85b/src/server/game/Globals/ObjectMgr.cpp#L75) and a [`switch` without any `default`](https://github.com/azerothcore/azerothcore-wotlk/blob/d0561c56df194aa9eff0f18b237664659153c85b/src/server/game/Globals/ObjectMgr.cpp#L7187).

2) How should we tackle a `case` statement that is empty when the `default` statement is empty or absent such as [`case GAMEOBJECT_TYPE_SUMMONING_RITUAL: break;`](https://github.com/azerothcore/azerothcore-wotlk/blob/d0561c56df194aa9eff0f18b237664659153c85b/src/server/game/Globals/ObjectMgr.cpp#L7159)?

### Describe the solution you'd like

I'd like the favored responses written into the [C++ Code Standards](https://www.azerothcore.org/wiki/cpp-code-standards) ([edit link](https://github.com/azerothcore/wiki/edit/master//docs/cpp-code-standards.md)) page so I or the community may follow them.

### Describe alternatives you've considered

Doesn't apply.

**Comment by Helias** [comment]
Adding cpp check https://github.com/azerothcore/azerothcore-wotlk/pull/15211 we are forced to add the `default` condition to avoid any possible warnings and prevent possible issues.

About empty cases like `GAMEOBJECT_TYPE_SUMMONING_RITUAL: break` we could comment them to remove a bit of overhead to the compiler, but if we decide to leave them, it's not an issue for me.
I do not know if the compiler applies some optimization in that case, but I think it does, so it should not add too much overhead during the run-time of the application
