### ISSUE TITLE
[Feature Request]: class rebalance (guide) page

### ISSUE THREAD

**Issue by MellianStudios** [azerothcore/wiki#793]
### Is your feature request related to a problem? Please describe.

Hello there so i would like a new wiki page to be created on topic "class rebalancing". To clarify i mean everything except spells/talents. For spells/talents there could be reference to spell editor and dbc editor.

This page should include detailed* description how to change each item listed below. But it is not intended to have duplicates meaning if several things are done in same place or same way it can be stated that "these N things are done like this". Im not sure how to word that because obviously stating code line of something is not good way maybe saying in which function it is but that can also change in future not that this couldnt be updated but it would be better to word it in a way that requires as low frequency of updates for this page as possible.

* detailed means that after reading it there should not be anything more to do required other than going and changing it (no more reasearch and/or searching through code or dbc/db files/columns)

I spent about an hour going across multiple classes gathering this list. If i missed anything that thing is also subject of this feature thus needed to be done and i would be happy if anyone helped finishing this list to be complete and include everything.

str to ap
agi to ap
agi to armor
agi to crit x2 (meele, ranged)
stam to hp
stam to pet stam
int to mana
int to spell crit
int to pet int
spirit to regen x2 (while castin, while not casting)
armor to dmg reduct
armor to pet armor
def rating
def to dodge block and parry
def to reduce chance to be critically hit
dodge rating
parry rating
block rating
block value to block value
resil to reduce chance to be critically hit
resil to reduce mana drain and crit dmg
resil to dmg reduct from players and pets
haste to cast speed
haste to global cooldown reduction
haste to melee attack speed
haste to ranged attack speed
crit rating
hit rating
exp rating
exp to reduce chance to be dodged or parried (this is probably not needed as it is implicite of rating conversion)
armor pene rating
ap rating
ap to pet ap
ap to pet spell dmg

One last important thing is threat. I know literally nothing about it i dont know if its core feature of class or if there is some base value for all classes or its purely from spells and talents. This needs to be found how is done and also stated on this page.

Im not best describer in world so if there will be anything unclear please ask in comments and i will clarify.

There will be bounty for this. For now i want to get this as complete as possible before placing it and in case that in process of doing it there will be sometething not foreseen found i know its not ideal to change description in middle of process but it is neccessary for this to be complete and in worst case im prepared to add more money.

Edit: I forgot to say that there are differences to this between classes so for example agi doesnt give armor to all classes. This also needs to be taken care of in a way that it is said how to change it so for example hunter has armor from agi and mage doesnt so how to change it so hunter doesnt have it and mage has it. It is very well possible that i missed something because i dont even know its happening but that is also in scope of this feature so if u find something related to this topic but not written here please write it in comments and it will become part of this feature. 

### Describe the solution you'd like

Everything is stated in first part

### Describe alternatives you've considered

None. I mean technically it could be done as video but there are no real alternatives to this

**Comment by ihm-tswow** [comment]
Working on this, friend will claim bounty once I'm done. I expect this to be done in 1~3 days as I have a crammed schedule at the moment

**Comment by MellianStudios** [comment]
even a week

i would prefer to take time and be sure that there is nothing missed

**Comment by MellianStudios** [comment]
i just got reminded that there is also difference by player level

**Comment by MellianStudios** [comment]
nice

do you feel like 50 is enough money for this ?

**Comment by ihm-tswow** [comment]
As currently described, yes, the price is good for this task. If you find more things you want explained we can discuss further pricing for those as well.

My understanding of your current needs involve:
- item -> stat calculations and modifiers
- stat -> stat calculations and modifiers
- level-based calculations and modifiers
- class-based calculations and modifiers

But would not involve
- Modifying spell/talent-based modifiers

Usually it can be seen from reading the functions I will point to how to do the latter as well, but how exactly will vary greatly for different stats and does require reading the source code around it a bit. The article will aim to give a starting point for expanding the work in these ways as well.

**Comment by MellianStudios** [comment]
item -> stat calculations and modifiers
by this you mean changing that for example 10 stamina on item would actually give more/less than 10 ?

**Comment by ihm-tswow** [comment]
Correct, but since you specified you also wanted calculations for stamina -> health, it will also include instructions for modifying that without modifying the input stamina amount (so that it should display right in the character window).

Some stats do not work like this and apply some multiplier into a percentage directly, and for those the procedure is simpler.

**Comment by MellianStudios** [comment]
well i wanted literally everything but item -> stat i didnt even think of and its not important for me but i guess its good to have it here in case some1 will find it useful in future

**Comment by ihm-tswow** [comment]
Some of the stats you have described actually work directly as item -> stat calculations.

If you wanted a to apply a transformation on, for example, haste rating to cast speed, that would be an item->stat calculation, as item haste rating is applied directly into the players casting speed percentage modifier. Combat ratings generally (but not always) work this way, while primary stats usually take a route through some other delayed calculation.

**Comment by MellianStudios** [comment]
so haste value in char info is just sum of items and actual property of character is only in form of % of speed ?

**Comment by ihm-tswow** [comment]
Correct. I will verify exactly how it works before I publish my work so there is no accidental writing to values that are also applied to an updatedata field (i.e. what you see in character window), I think I understand what things you want to change and how that should work; affecting percentage or "end" values without hacking in cheat values on the displayed input itself.

**Comment by ihm-tswow** [comment]
I will warn you that pet stats do not work the way you probably assume from these points in azerothcore. I am somewhat unfamiliar with them (or how they are "supposed" to work) so they will require some additional verifications, just be prepared there are hardcodes upon hardcodes applied to them so the section will be a bit long to explain xD

**Comment by MellianStudios** [comment]
well that (learning how it works) is part of this...i got very limited knowledge of core so something i get wrong expectation about and something i dont have any because i just have no idea

maybe it could be helpful if i said exactly what i want to do with this so i want big numbers but that obviously doesnt work because if i get item with 1M haste my casts are instant because it is like 15000% cast speed and i want to change it properly not hackfixing it....in past i tried some smaller things for example i experimented with removing armor gain from agility and other additional stats from base stats by commenting out lines like `value += GetStat(STAT_AGILITY) * 2.0f;` in game/Entities/unit/StatSystem or scaling it down like this `value = value * sConfigMgr->GetOption<float>("Stats.Armor.Reduction", 0.05f);` but i didnt feel like that is how it is supposed to be done without side effects of bugs

**Comment by ihm-tswow** [comment]
That's precisely the kind of thing I'm writing the article for. I have a bit of a personal interest in this (but for the opposite purpose, I'm trying to flatten wow's progression curve), and it's something I've been working on for some time. 

Of course, you'll need to do some tweaking on the values yourself, but this should give you the places you want to modify for the kind of transformations you probably want to apply 🙂

**Comment by MellianStudios** [comment]
i saw TS wow is intending to create something of this kind in way of very simple and straightforward customization of stat formulas but im not keeping eye on progress

**Comment by ihm-tswow** [comment]
Completed here:
https://gist.github.com/ihm-tswow/74e620b8918517ade7fccc31640ee0bc
