### ISSUE TITLE
DBC Documentation

### ISSUE THREAD

**Issue by Kitzunu** [azerothcore/wiki#84]
- [ ] Add a "Group" page for DBC files

- [ ] Add documentation for all DBC files

**Comment by BarbzYHOOL** [comment]
https://wowdev.wiki/Main_Page has all dbc stuff for wotlk (which is independent from the CORE)

**Comment by FrancescoBorzi** [comment]
I would keep just a reference to that DBC wiki in our own wiki, it makes no much sense to duplicate the work

**Comment by Kitzunu** [comment]
Oh, did not know about that one.
Well if there already is full Documentation of it it's just a waste of time to dup it
