### ISSUE TITLE
[Feature Request]: Add the new smart_scripts PRs

### ISSUE THREAD

**Issue by Gultask** [azerothcore/wiki#843]
### Is your feature request related to a problem? Please describe.

Missing:
https://github.com/azerothcore/azerothcore-wotlk/pull/13880
https://github.com/azerothcore/azerothcore-wotlk/pull/13947
https://github.com/azerothcore/azerothcore-wotlk/pull/14811

New: https://github.com/azerothcore/azerothcore-wotlk/pull/14981

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by Kitzunu** [comment]
83203780bc96356a5aca2488852a773cf796124f
