### ISSUE TITLE
[Feature Request]: gameobject-template-addon fields description

### ISSUE THREAD

**Issue by Helias** [azerothcore/wiki#857]
### Is your feature request related to a problem? Please describe.

there are some new fields `artkit0, artkit1, artkit2, artkit3`  with no description or mention in the wiki page

### Describe the solution you'd like

we should have a description for these fields

### Describe alternatives you've considered

I will check the original PR that added these fields but for now I know nothing about them
I can surely add the sql structure description

**Comment by heyitsbench** [comment]
I'm going to be re-vamping *a lot* of wiki pages in tandem with [this AC PR](https://github.com/azerothcore/azerothcore-wotlk/pull/14503), so I can probably handle this with that, assuming my description for these fields is up to snuff. 😛
