### ISSUE TITLE
Missing DBC related pages

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/wiki#86]
This is linked in several pages like on TC http://www.azerothcore.org/wiki/ChrClasses

but it doesn't exist, maybe we should create that page or link to something on wowdev (but that external site is not known for being pretty and easy to navigate so maybe not a good idea for only the list of classes/races flags)

**Comment by Kitzunu** [comment]
I spose I could copy ChrClasses from wowdev or TC, doesnt look to be too much work after looking at https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129967/ChrClasses

But it's up to you guys how you want it I suppose.

I was going to do more work today, but things came up and tomorrow I start my summer work, but I will do what I can when I have time

**Comment by BarbzYHOOL** [comment]
Well, compare to this page https://wowdev.wiki/DB/ChrClasses

Seems like the wowdev page is not noob friendly, right? :D

**Comment by Kitzunu** [comment]
The 3.3.5 part is quite alright :P

**Comment by BarbzYHOOL** [comment]
no it doesn't list the flags

**Comment by Kitzunu** [comment]
Oh I missed that one, mb, been kinda overwhelmed today ^^

**Comment by Kitzunu** [comment]
![image](https://user-images.githubusercontent.com/24550914/59385531-dddcec80-8d64-11e9-9bd1-647e41480e88.png)

If only things were more simple O.o

**Comment by FrancescoBorzi** [comment]
I've added some dbc docs, maybe we should have a list of what is missing

**Comment by BarbzYHOOL** [comment]
chrclasses and chrraces at least
