### ISSUE TITLE
[Feature Request]: Update SQL standards to point out that nested SELECT queries could cause the autoupdater to hang up for MariaDB users

### ISSUE THREAD

**Issue by Gultask** [azerothcore/wiki#861]
### Is your feature request related to a problem? Please describe.

Title

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

This could use further testing.

File 2022_11_03_07.sql: https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/updates/db_world/2022_11_03_07.sql
This file can take several minutes to run for MariaDB users.
The file was originally created as part of a revamp for Outland gameobjects, and was made in conjunction with several other big PRs, making several thousand insertions. However, only this file takes several minutes to run for MariaDB users.
The only difference between this file and the others is the presence of these 2 lines:
```
DELETE FROM `pool_template` WHERE `entry` IN (SELECT `pool_entry` FROM `pool_gameobject` WHERE `guid` IN (SELECT `guid` FROM `gameobject` WHERE `id` IN (182954, 182953, 182952, 182957, 182954, 182956, 182951, 182959, 182958) AND `map`=530));
DELETE FROM `pool_gameobject` WHERE `guid` IN (SELECT `guid` FROM `gameobject` WHERE `id` IN (182954, 182953, 182952, 182957, 182954, 182956, 182951, 182959, 182958) AND `map`=530);
```
Which contain nested SELECT queries. In HeidiSQL on my end, the file takes around 7.5s to run, but there is a noticeable pause on these 2 queries.

**Comment by Helias** [comment]
it's weird, nested select queries are often better than join queries and there are no alternatives for them except writing manually the list of IDs and removing the second select.

**Comment by Kitzunu** [comment]
Or just dont use maria 🤷

**Comment by Kitzunu** [comment]
I will close this as we have taken the decision to first and foremost optimize the core for using MySQL
