### ISSUE TITLE
[Feature Request]: add Grphana tutorial

### ISSUE THREAD

**Issue by mpfans** [azerothcore/wiki#865]
### Is your feature request related to a problem? Please describe.

my server many players, too low hardware resources and enough bandwidth, but the `Update time diff` value is too large, resulting in spell delay

### Describe the solution you'd like

At present, there is no complete tutorial for AC core to use `Grphana`. It is recommended to add . Thank 

### Describe alternatives you've considered

none

**Comment by Kitzunu** [comment]
https://www.azerothcore.org/wiki/monitoring-azerothcore-with-grafana
