### ISSUE TITLE
Anchors with uppercase letters are automatically broken

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#91]
When an anchor link has one or more uppercase letter, its link will not work.

For example, open the page: http://www.azerothcore.org/wiki/creature_template#difficulty_entry_X

Any fully-lowercase anchor link like `difficulty_entry_1` will work.
Any anchor link that has uppercase letters like `KillCredit1` will **NOT** work.

**Comment by wizzymore** [comment]
I think this can be closed

**Comment by BarbzYHOOL** [comment]
it's only in creature_template?
