### ISSUE TITLE
[Bug report]: (get errors when build AC server on freebsd 13.2)

### ISSUE THREAD

**Issue by lotest** [azerothcore/wiki#912]
### Describe the bug

OS: FreeBSD 13.2
clang: 14.0.5
cmake: 3.27.0 / 3.26.1
boost-all: 1.82.0
mysql: mysql80

When compile ac server, encount the errors, that makes me can't build the executale files:
1. common/Time.cpp
``` shell
[  7%] Building CXX object src/common/CMakeFiles/common.dir/Utilities/Timer.cpp.o
/home/xxx/workspace/azeroth-core/src/common/Utilities/Timer.cpp:250:17: fatal error: arithmetic on a pointer to the function type 'char *(int, int)'
    return time + timezone;
                ^ ~~~~~~~~
1 error generated.
--- src/common/CMakeFiles/common.dir/Utilities/Timer.cpp.o ---
*** [src/common/CMakeFiles/common.dir/Utilities/Timer.cpp.o] Error code 1

make[2]: stopped in /usr/home/xxx/workspace/azeroth-core/build
1 error

```

After comment the code "timezone" at the line 250 in Time.cpp file, the error changes to the below:

2. Linking CXX executable authserver
``` shell
[ 16%] Linking CXX executable authserver
ld: error: undefined symbol: std::__1::enable_if<!(std::is_base_of_v<std::__1::basic_string_view<char, std::__1::char_traits<char> >, long long>), void>::type PreparedStatementBase::SetValidData<long long>(unsigned char, long long const&)
>>> referenced by PreparedStatement.h:80 (/home/lqf/workspace/azeroth-core/src/server/database/Database/PreparedStatement.h:80)
>>>               AppenderDB.cpp.o:(AppenderDB::_write(LogMessage const*)) in archive ../database/libdatabase.a
>>> did you mean: std::__1::enable_if<!(std::is_base_of_v<std::__1::basic_string_view<char, std::__1::char_traits<char> >, signed char>), void>::type PreparedStatementBase::SetValidData<signed char>(unsigned char, signed char const&)
>>> defined in: ../database/libdatabase.a(PreparedStatement.cpp.o)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /usr/home/xxx/workspace/azeroth-core/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/xxx/workspace/azeroth-core/build
*** Error code 1

Stop.
make: stopped in /usr/home/xxx/workspace/azeroth-core/build

```

### To reproduce

i. install FreeBSD 13.2
ii. Follow instructions : https://www.azerothcore.org/wiki/freebsd

### Expected behavior

Could build executable (eg. authserver,  worldserver) server files on freebsd. 

### Screenshots

![WV1RA@95I)84_3J_JQHBSBS](https://github.com/azerothcore/wiki/assets/3821747/ea1c1fe0-3ad1-4652-b03d-a63037a006fa)

### Desktop

OS: FreeBSD 
Version: 13.2

### Smartphone

--

**Comment by Kitzunu** [comment]
Well freebsd is not a supported OS, so there are high chances you will find errors.

I suggest you use a supported OS instead, like Ubuntu

**Comment by Kitzunu** [comment]
![Screenshot_20230722_175108_Chrome](https://github.com/azerothcore/wiki/assets/24550914/d58c4f55-bcba-45ef-8293-687bfe52f5f0)
