### ISSUE TITLE
creature_template.AIName should be updated

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/wiki#92]
I guess the starting point would be looking into:

`server/game/AI/CreatureAIRegistry.cpp`

to check all possible types.

Also this query can help:

```
SELECT DISTINCT(AIName) FROM creature_template 
```

**Comment by Stoabrogga** [comment]
Can this be closed?

**Comment by FrancescoBorzi** [comment]
if the information provided in http://www.azerothcore.org/wiki/creature_template#ainame
is correct, then we can close this issue

**Comment by Stoabrogga** [comment]
Ok, I see, most of the description is missing. I'll take a look at this.
