### ISSUE TITLE
[Bug report]: Docker compose cannot start because of unsupported versions

### ISSUE THREAD

**Issue by alecsci** [azerothcore/wiki#991]
### Describe the bug

`ERROR [gitlab-wiki-theme 4/4] RUN bundle install --gemfile=.env-files/Gemfile.gitlab                           5.5s

 > [gitlab-wiki-theme 4/4] RUN bundle install --gemfile=.env-files/Gemfile.gitlab:
2.194 Fetching gem metadata from http://rubygems.org/...........
5.291 Fetching gem metadata from http://rubygems.org/.
5.299 Resolving dependencies...
5.431 ffi-1.17.0-x86_64-linux-musl requires rubygems version >= 3.3.22, which is
5.431 incompatible with the current version, 3.1.2
failed to solve: process "/bin/sh -c bundle install --gemfile=.env-files/Gemfile.gitlab" did not complete successfully: exit code: 5`

### To reproduce

Run the docker-compose up
Wait until it crashes

### Expected behavior

Server starts successfully to serve markdown pages 

### Desktop

Windows 11 x64, Ubuntu 20

### Smartphone

Browser

**Comment by Helias** [comment]
I am able to reproduce the issue

**Comment by Yehonal** [comment]
This should be related https://github.com/Drassil/git-wiki-theme/issues/108

if so, please close it. WIll be addressed on the original drassil repo

**Comment by Yehonal** [comment]
THis should be fixed now https://github.com/Drassil/git-wiki-theme/issues/108

**Comment by alecsci** [comment]
@Yehonal 
There is a new error now: 
jekyll 3.10.0 | Error:  Could not locate the included file 'git-wiki/defines/defines.html' in any of ["/srv/jekyll/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.

**Comment by alecsci** [comment]
Hi @TheSCREWEDSoftware for the new error try to start the project locally.

I don't have access to a laptop until the end of November, sorry

**Comment by TheSCREWEDSoftware** [comment]
Dont have to be sorry, i will see if i've time to check this. If i dont reply something and you have the pc back, say something here
