### ISSUE TITLE
"RewardMailDelay" in "quest_template" and "quest_template_addon" - help needed

### ISSUE THREAD

**Issue by TheSCREWEDSoftware** [azerothcore/wiki#995]
### Is your feature request related to a problem? Please describe.

I need some guidance as I'm editing quest_template_addon.

1) Fixing my Error (done)
2) Fixing Headings (done)
3) Fixings Links or Links with Headings (finishing)

 [RewardMailDelay](https://www.azerothcore.org/wiki/quest_template_addon) 
 You will see that in RewardMailDelay redirects you to [quest_template](https://www.azerothcore.org/wiki/quest_template#rewardmailtemplateid)
 
 That doesn't exist (nor does it exist in the DB Database) I either pressume this wasn't implemented by mistake or intended. As this wiki content is based on TrinityCore? (correct me if wrong) But in TC their Wiki
 
 quest_template_addon [RewardMailDelay](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/34897928/quest_template_addon-RewardMailDelay) goes to quest_template [RewardMailTemplateId](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130261/quest_template#quest_template-RewardMailTemplateId) that goes to loot_template [quest_mail_loot_template](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130202/loot_template)

I just need some orientation on this.

**Comment by Helias** [comment]
if we have some deleted or non-existing columns in the wiki we can delete them

**Comment by TheSCREWEDSoftware** [comment]
Thanks for the clarification helias, I will b e closing this question/issue.
